package ru.introguzzle.parser.json.entity;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.Serial;
import java.util.*;
import java.util.function.BiFunction;
import java.util.function.Function;

/**
 * Represents a JSON array as a list of objects.
 * <p>
 * This class extends {@link ArrayList} to provide a structure for JSON arrays,
 * enabling easy serialization to and from JSON strings. It implements
 * the {@link JSONStringConvertable} interface.
 * </p>
 */
public class JSONArray extends ArrayList<Object> implements JSONStringConvertable {

    @Serial
    private static final long serialVersionUID = -1731069894963023770L;

    /**
     * Retrieves the value at the specified index and casts it to the desired type.
     *
     * @param index the index of the value to retrieve
     * @param type  the class type to cast to
     * @param <T>   the type to be returned
     * @return the value at the specified index cast to the specified type
     */
    public <T> T get(int index, Class<? extends T> type) {
        return type.cast(get(index));
    }

    /**
     * Retrieves the value at the specified index and casts it to the desired type,
     * or returns a default value if the index is out of bounds or the value is null.
     *
     * @param index        the index of the value to retrieve
     * @param type         the class type to cast to
     * @param defaultValue  the default value to return if the index is out of bounds or the value is null
     * @param <T>          the type to be returned
     * @return the value at the specified index cast to the specified type, or the default value
     */
    public <T> T get(int index, Class<? extends T> type, T defaultValue) {
        Object value = get(index);
        if (value == null) {
            return defaultValue;
        }
        return type.cast(value);
    }

    /**
     * Converts this JSONArray to a JSONObject using a specified key extractor function
     * and an optional remapping function for handling duplicate keys.
     *
     * @param keyExtractor a function that extracts a key from each element in the JSONArray.
     *                     This key will be used in the resulting JSONObject.
     * @param remappingFunction an optional function that allows for custom remapping of keys
     *                          when a duplicate key is detected in the JSONObject.
     *                          This function takes the current value and the existing key
     *                          as parameters, and should return the new key to be used
     *                          in the JSONObject. If no remapping function is provided or
     *                          if no duplicate key is found, the original key is used.
     * @return a JSONObject constructed from the elements of this JSONArray, with keys
     *         generated by the keyExtractor and remapped as necessary by the remappingFunction.
     */

    public
    JSONObject toJSONObject(@NotNull Function<Object, String> keyExtractor,
                            @Nullable BiFunction<Object, String, String> remappingFunction) {
        JSONObject object = new JSONObject();

        for (Object value : this) {
            String key = keyExtractor.apply(value);
            if (remappingFunction != null && object.containsKey(key)) {
                key = remappingFunction.apply(value, key);
            }

            object.put(key, value);
        }

        return object;
    }

    @Override
    public Iterator<?> getIterator() {
        return iterator();
    }

    @Override
    public String getOpeningSymbol() {
        return "[";
    }

    @Override
    public String getClosingSymbol() {
        return "]";
    }
}
