# Простой ключ-значение
name: "Example Configuration"  # строка

# Числа, булевы значения и null
version: 2.0           # число с плавающей точкой
debug: true            # булево значение
max_retries: 5         # целое число
cache_enabled: null    # значение null

# Списки (массивы)
items:
  - "item1"            # строка
  - "42"               # число
  - "true"             # булево значение
  - "null"             # null

# Словари (ассоциативные массивы)
database:
  host: "localhost"
  port: 5432
  user: "admin"
  password: "secret"

# Вложенные структуры
servers:
  us-east:
    name: "East US Server"
    ip: "192.168.1.1"
    enabled: true
  eu-west:
    name: "West Europe Server"
    ip: "192.168.2.1"
    enabled: false

# Списки объектов
users:
  - name: "Alice"
    age: 30
    role: "admin"
  - name: "Bob"
    age: 25
    role: "user"

# Многострочная строка | (сохранение всех переносов)
description: |
  This is a long description that will span multiple lines.
  Each line will be preserved exactly as it appears.

# Многострочная строка > (переносы заменяются пробелами)
comments: >
  This is another long comment.
  Line breaks will be replaced by spaces in the final string.

# Ссылки и якоря (для переиспользования значений)
default_user: &default_user
  name: "Guest"
  role: "guest"

active_user:
  <<: *default_user   # Подстановка значения через ссылку на якорь
  age: 28

# Порядковые множества (множество уникальных элементов)
unique_items: !!set
  ? "item1"
  ? "item2"
  ? "item3"

    # Пример использования метаданных в YAML через метки
  !!map
metadata:
  created_by: "system"
  version: 1.1

# Индикация строки в одной линии
inline: [item1, item2, item3]

# Многострочная карта в одной линии
complex_inline: { key1: value1, key2: value2 }

# Теги для явного указания типа данных
explicit_types:
  integer: !!int "42"
  float: !!float "3.14159"
  boolean: !!bool "true"
  null_value: !!null "null"
